source "https://rubygems.org"

gem "rails", "~> 7.2.2"
gem "sqlite3", ">= 1.4"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

group :development, :test do
  gem 'cypress-on-rails', path: '../../'
  gem 'database_cleaner'
end
